version: 2
jobs:
  build:
    working_directory: ~/repo
    environment:
      - AWS_S3_BUCKET_NAME: millcrepe.net
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy to S3 if branch is Master.
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build/ s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
            # fi
