version: 2
jobs:
  build:
    working_directory: ~/repo
    environment:
      - AWS_S3_BUCKET_NAME: millcrepe.net
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - checkout
      - run:
          name: Deploy to S3 if branch is Master.
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn start && aws s3 sync src/ s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
            # fi
